### ISSUE TITLE
Cmake fails with "install FILES given no DESTINATION"

### ISSUE THREAD

**Issue by jtdaugherty** [intel/dynamic-application-loader-host-interface#6]
When I execute the first build step as of `9fba7df2d1ce6dde95c639d8ef1afb4509ffba45`, I get this:
```
dynamic-application-loader-host-interface$ cmake .
CMake Error at CMakeLists.txt:274 (install):
  install FILES given no DESTINATION!
```
What am I missing?

**Comment by jtdaugherty** [comment]
Other context that might be helpful:
 * Ubuntu 16.04.1
 * `cmake` 3.5.1

**Comment by jlahav** [comment]
Hi. Checking line 274 of CMakeLists.txt shows that the missing value is of the variable SYSTEMD_DIR.
Since you use Ubuntu 16.04 which should already be using systemd I don't see an obvious reason for the error.

Please take a look [here](https://github.com/01org/dynamic-application-loader-host-interface/blob/master/CMakeLists.txt#L237) and check the output of the command
`pkg-config systemd --variable=systemdsystemunitdir`
The output of the command should have been the missing value.

**Comment by jtdaugherty** [comment]
It turned out that I didn't need to run this software at all, so in that sense my problem went away. I also won't have time to track it down. Still, it's probably worth investigating - but if you would rather close this ticket, that's okay with me. Thank you!

**Comment by jlahav** [comment]
Thanks for the report.

**Comment by chherder** [comment]
Hey - I know that this comment is closed, but I ran into the same issue and was able to resolve it.  In my case, it turns out that SYSTEMD_DIR wasn't being set earlier because I didn't have pkg-config installed.

Running `apt-get install pkg-config` before `cmake .` resolved the issue.

**Comment by jlahav** [comment]
Thank you for confirming. I'll add pkg-config to the list of dependencies.

**Comment by smritipillai** [comment]
This is what the error (https://pastebin.com/raw/85JizEdJ) I get if I type apt-get install pkg-config before cmake. Can anyone help?

**Comment by kyl3r92** [comment]
@smritipillai try "sudo apt-get install pkg-config" (just add sudo) - if you are not root, it will promt you for a password - if you don't have that you can't install pkg-config!
